-- data Bool = True | False
--
-- ?? represents cardinality
-- True | False = ??
-- True + False = ??
-- 
-- False and True both == 1
-- 1 + 1 == ??
-- 1 + 1 == 2
--
--
-- data BigSmall = Big Bool | Small Bool
--
-- Big Bool | Small Bool == ??
-- Big Bool + Small Bool == ?
--
-- Big   Bool == 2
-- Small Bool == 2
--
-- 2 + 2 == 4
--
--
-- data NumberOrBool = Numba Int8 | BoolyBool Bool
--
-- Numba Int8 | BoolyBool Bool == ??
--
-- Numba Int8 == 256
--
-- BoolyBool Bool == 2
--
-- Numba Int8 + BoolyBool Bool == ??
-- 256 + 2 == 258
